### ISSUE TITLE
Question: Playstore

### ISSUE THREAD

**Issue by rodrigolmacedo** [mkobuolys/flutter-design-patterns#23]
can i publish your work(app) in playstore? i like to study when travelling. by the way awesome work.

Good work!

**Comment by MangirdasKazlauskas** [comment]
Hi, unfortunately, the application is not quite production ready. The article series is still not done (there are some design patterns left), also I have some ideas on how to improve the performance and UX of the application, so maybe I will write an article on that, too. After that, I will probably publish the application myself :)

P.S. if you want to have an application on your physical device, just pull the code and build the application by connecting your device and running `flutter run --release`. Thus, you will have the same experience as installing the application from the Playstore.
