### ISSUE TITLE
Add better image view

### ISSUE THREAD

**Issue by mkobuolys** [mkobuolys/flutter-design-patterns#27]
It would be nice to zoom images provided in the markdown files of the design patterns. 

This feature is already implemented with https://github.com/mkobuolys/flutter-design-patterns/pull/24, but due to changes in the codebase and migration to Dart null-safety the code is already outdated and this solution should be reworked.

**Comment by prateekmedia** [comment]
You can use flutter fix or dart migrate command to do so.

**Comment by mkobuolys** [comment]
> You can use flutter fix or dart migrate command to do so.

Dart migration is not a problem anymore - the project is already migrated. However, the code base for the project changed a lot since #24 was implemented, so this should be reworked anyway.
