### ISSUE TITLE
Back Buttons not working

### ISSUE THREAD

**Issue by lucianojung** [mkobuolys/flutter-design-patterns#30]
When I deploy the App for flutter web the Back-Buttons not working anywhere in the App.
![image](https://user-images.githubusercontent.com/33691403/113604543-bb0c7e00-9645-11eb-9319-aa78673fcf4b.png)

**Comment by mkobuolys** [comment]
Hi, thanks for registering the issue. For now, I have only built the app for Android/iOS, meaning I haven't tested the app on any other platform so you could expect design flaws and other bugs on Web/Desktop versions.

**Comment by theiskaa** [comment]
This issue was fixed, in [Web-Support PR](https://github.com/mkobuolys/flutter-design-patterns/pull/31).
@lucianojung you can just make a simple try-catch block to avoid this issue, like: 
```dart
 IconData get getValidIcon {   
   IconData icon;   
   try {    
       Platform.isAndroid  ? icon = Icons.arrow_back : icon = Icons.arrow_back_ios; 
   } catch (_) {   
       icon = Icons.arrow_back;  
    }
    return icon;
  }
```

**Comment by mkobuolys** [comment]
The bug was fixed with https://github.com/mkobuolys/flutter-design-patterns/pull/31, hence closing the issue.
