### ISSUE TITLE
Use github CI to auto generate and upload apk to release.

### ISSUE THREAD

**Issue by prateekmedia** [mkobuolys/flutter-design-patterns#33]
Sample CI:
https://github.com/prateekmedia/flutube/blob/main/.github/workflows/generate_apk.yml

**Comment by mkobuolys** [comment]
Hi! Currently, I do not plan to release this project as an app for Android. More likely, I will deploy this as a Flutter Web application and/or PWA, so you could use it without the need to download the app from the App Store/Google Play Store. Hence, closing this issue for now. Thanks for your contribution, though!

**Comment by II11II** [comment]
Hi @mkobuolys 🖐,
Is there any news about the PWA version of this code?

**Comment by mkobuolys** [comment]
Hey @II11II, I have already bought a domain for the project (!!!) but did not find time to get to it. Hopefully, that would happen next month but I don't want to promise anything.
