### ISSUE TITLE
Conflicting outputs were detected

### ISSUE THREAD

**Issue by cofirazak** [mkobuolys/flutter-design-patterns#36]
Trying to install app by instructions in readme:

<img width="1440" alt="Screenshot 2021-09-21 at 18 44 13" src="https://user-images.githubusercontent.com/2613578/134203146-8916cde6-a787-45f3-afeb-23de2c196abc.png">

**Comment by cofirazak** [comment]
`rm -rf lib/navigation/router.gr.dart`
did fix that issue, but then after flutter run i got this:
<img width="1440" alt="Screenshot 2021-09-21 at 18 50 43" src="https://user-images.githubusercontent.com/2613578/134204236-2aaf2376-aed3-4fea-9470-7a6c5d953217.png">
<img width="1440" alt="Screenshot 2021-09-21 at 18 50 56" src="https://user-images.githubusercontent.com/2613578/134204209-a10f5e5d-3234-4440-96db-2f7cd823369f.png">

**Comment by mkobuolys** [comment]
Hi, @cofirazak. As mentioned in the error message, to the `flutter pub run build_runner build` command, add an extra parameter like this: `flutter pub run build_runner build --delete-conflicting-outputs`. Let me know if that helps.
