### ISSUE TITLE
Code selection is not visible

### ISSUE THREAD

**Issue by yahu1031** [mkobuolys/flutter-design-patterns#43]
Whatever code I select, I can't see if it is selected or not.

The first code block I actually selected.
The second, I didn't.
![Screenshot 2022-06-07 at 6 37 03 PM](https://user-images.githubusercontent.com/35523357/172387375-0f7f3e4e-92b0-400a-8208-c7f6214d6dd3.png)

Maybe add a color to `SelectableText` widget.

**Comment by mkobuolys** [comment]
Thanks for the feedback, I will take a look at this 👍🏻
