### ISSUE TITLE
how do you update the 'isInitiallyExpanded' parameter  ?  in the application it works but here in this repo i cant find where you do that update 

### ISSUE THREAD

**Issue by peymanrahi** [mkobuolys/flutter-design-patterns#56]
https://github.com/mkobuolys/flutter-design-patterns/blob/04514284d1e1a55241e3b3a5bd40533ed5ba6f2f/lib/widgets/design_patterns/composite/directory.dart#L39

**Comment by mkobuolys** [comment]
Probably talking about this: https://github.com/mkobuolys/flutter-design-patterns/blob/master/lib/widgets/design_patterns/composite/composite_example.dart#L39?
