### ISSUE TITLE
duplication in turn lightOn 

### ISSUE THREAD

**Issue by peymanrahi** [mkobuolys/flutter-design-patterns#58]
https://github.com/mkobuolys/flutter-design-patterns/blob/66707f0cfbba37da360b3b470d833c17a0062a84/lib/design_patterns/facade/facades/smart_home_facade.dart#L56C1-L56C1

hi, first of all, I want to thank you  for your amazing repo,

I just noticed that in the referenced function (stopStreaming) you turned the lights On which is already on, based on your previous function (startStreaming), and is there any reason to add  turnLightsOn()  again? 

thank you in advance for your clarification

  void startStreaming(SmartHomeState smartHomeState) {
    smartHomeState.lightsOn = smartHomeApi.turnLightsOn();
    smartHomeState.tvOn = tvApi.turnOn();
    gamingFacade.startStreaming(smartHomeState);
  }

  void stopStreaming(SmartHomeState smartHomeState) {
    gamingFacade.stopStreaming(smartHomeState);
    smartHomeState.tvOn = tvApi.turnOff();
    smartHomeState.lightsOn = smartHomeApi.turnLightsOn();
  }

**Comment by mkobuolys** [comment]
Hey, nothing specific, just to ensure the state is correct after calling `stopStreaming()`. In the current example (using switches to turn the mode ON/OFF AND preventing switching other modes while one of them is ON), I agree that this is redundant and could be removed from the method. However, in the code (let's say, you are building your custom UI and using this exposed facade), nothing prevents you from calling the `stopStreaming()` without calling `startStreaming()` beforehand, thus sometimes it makes sense to ensure the final state that you want to get into.

**Comment by mkobuolys** [comment]
Assuming that my previous answer makes sense, closing the issue.
